spring:
    datasource:
        username: dongbao
        password: dongbao
        url: jdbc:mysql://localhost:55001/msb_dongbao_mall?useSSL=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
        driver-class-name: com.mysql.cj.jdbc.Driver
    profiles:
        active: dev
mybatis-plus:
    configuration:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    global-config:
        db-config:
            logic-delete-value: 1
            logic-not-delete-value: 0
