spring:
    datasource:
        username: dongbao
        password: dongbao
        url: jdbc:mysql://localhost:3306/mca_dongbao?useSSL=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
        driver-class-name: com.mysql.cj.jdbc.Driver
    profiles:
        active: dev
    redis:
        database: 1
        host: 127.0.0.1
        password:
        port: 6379
        timeout: 3000
        jedis:
            pool:
                max-idle: 500
                min-idle: 50
                max-active: 2000
                max-wait: 1000
        testOnBorrow: true
mybatis-plus:
    configuration:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    global-config:
        db-config:
            logic-delete-value: 1
            logic-not-delete-value: 0
